### ISSUE TITLE
Issue with Cairo Timezone

### ISSUE THREAD

**Issue by rasmitam** [libical/vzic#13]
The actual timezone for Cairo is UTC +2 reference : https://www.timeanddate.com/time/zone/egypt/cairo
and for 2020 — 2029 | No changes, UTC +2 hours all of the period, but zoneinfo Cairo.ics shows +3
even though TZOFFSETTO:+0200 why the result returned is +3

N:Africa/Cairo
X-PROLEPTIC-TZNAME:LMT
BEGIN:STANDARD
TZNAME:EET
TZOFFSETFROM:+020509
**TZOFFSETTO:+0200**
DTSTART:19001001T000000
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:EEST
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
DTSTART:19400715T000000
RDATE:19410415T000000

**Comment by minichma** [comment]
Is this still an issue? The relevant zone info [can be found here](https://github.com/minichma/tzdbics/blob/f1017ef6d042bb793f21a73037468c288a2ac54d/zoneinfo/Africa/Cairo.ics#L31-L46). It states, that the offset is +2h starting frrom 20140926T0000, which seems to be correct. If not, could you please explain in more detail what you think is wrong?

**Comment by winterz** [comment]
closing as no response in a long time. 
please re-open if the issue persists
