### ISSUE TITLE
Able to compile but not able to generate zoneinfo from tzdata2021b latest release db

### ISSUE THREAD

**Issue by rasmitam** [libical/vzic#14]
Used tzdata2021b  latest release data.Compilation went fine.
Run ./vzic --pure
Getting this error "Can't format RRULE - out of bounds. Month: 2 Day number: 31"

**Comment by minichma** [comment]
I assume that this has been fixed with https://github.com/libical/vzic/commit/6ace991e2e123fb4857f8e155ea9d52dee0caebd. Can you confirm?

**Comment by winterz** [comment]
closing since no response in a long time.
please re-open if the problem persists.
