### ISSUE TITLE
Non-standard property TZUNTIL output for some zones

### ISSUE THREAD

**Issue by benfortuna** [libical/vzic#15]
The change is actually quite old, but for some reason has only output for some zones in recent tzdata definitions (e.g. `Africa/Casablanca`:

https://github.com/libical/vzic/commit/69a3ec80265c6a1e46a33dd8894d830ba552107d

<img width="421" alt="image" src="https://user-images.githubusercontent.com/984966/152634815-64e5a276-1247-459d-b4d7-d631ad7c55c0.png">

This is causing parsing issues when using these timezones:

https://github.com/ical4j/ical4j/issues/545

Is there a documented definition of the TZUNTIL property, as I don't see it in RFC5545.

**Comment by winterz** [comment]
@ksmurchison added TZUTIL over 4 years ago.  

I see some mention of TZUTIL in rfc7808 "Time Zone Data Distribution Service".  Ken would have more info.

**Comment by benfortuna** [comment]
Oh great thanks. We may just need to implement some additional properties in ical4j to support this.

**Comment by ksmurchison** [comment]
I'm surprised that Mike Douglass hasn't added support for TZUNTIL in ical4j already.

**Comment by benfortuna** [comment]
@ksmurchison yes I did double-check if we already had support for it. Anyway it should be quite trivial to add.
