### ISSUE TITLE
Has vzic moved from soureforge to github.com/libical ?

### ISSUE THREAD

**Issue by dilyanpalauzov** [libical/vzic#8]
The IANA Time Zone Database https://www.iana.org/time-zones publishes https://data.iana.org/time-zones/releases/tzdb-2019c.tar.lz (Complete Distribution (Data, Code and Extras)).  Its tz-link.html contains:
```html
<li><a href="https://sourceforge.net/projects/vzic/">Vzic</a> is a <a href="https://en.wikipedia.org/wiki/C_%28programming_language%29">C</a>
program that compiles<code><abbr>tz</abbr></code> source into iCalendar-compatible VTIMEZONE files.  Vzic is freely available under the <a href="https://www.gnu.org/copyleft/gpl.html"><abbr>GNU</abbr>General Public License (<abbr title="General Public License">GPL</abbr>)</a>.</li>
```
This states, that vzic can be downloaded from https://sourceforge.net/projects/vzic/ and the last published vzic 1.3 there is from 2006.

https://github.com/libical/vzic does make changes on vzic, but contains no releases.

Is the development of vzic was moved from sourceforge.net/projects/vzic to github.com/libical , then IANA shall be told to update its tz-link.html file.

**Comment by joycebrum** [comment]
I also would like to know ➕

**Comment by winterz** [comment]
I just send this to tz.iana.org

```
Hi,
I'm the current maintainer of vzic.
We moved the project from sourceforge to github many years ago
and I've been informed that your tz-link.html page still points
to the old sourceforge url.

Please update tz-link.html so that the vzic link points to https://github.com/libical/vzic
```
